System info screen
keyboardio/Chrysalis pull request #575
Opened 2020-10-08 12:29 UTC by algernon

This adds a new screen to Chrysalis, which allows one to let Chrysalis collect information about the system (OS, Chrysalis itself, and any connected device) and bundle that up in a zip file they can send us.

![Screenshot from 2020-10-08 14-22-15](https://user-images.githubusercontent.com/17243/95457878-bf472f80-0971-11eb-95ab-017a9749be72.png)

Clicking the "Collect Information" button will gather the info, and then pop up a save dialog:

![Screenshot from 2020-10-08 14-22-37](https://user-images.githubusercontent.com/17243/95457929-cec67880-0971-11eb-815b-e96577aeef69.png)

At the moment, the following files are included in the zip file:

```
❯ unzip -l chrysalis-debug.bundle.zip
Archive:  chrysalis-debug.bundle.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      321  2020-10-08 12:23   osInfo.json
       20  2020-10-08 12:23   chrysalis.json
    34849  2020-10-08 12:23   logs.json
    24319  2020-10-08 12:23   device.json
---------                     -------
    59509                     4 files
```

## `osInfo.json`

```json
{
  "platform": "linux",
  "distro": "Debian GNU/Linux",
  "release": "10",
  "codename": "buster",
  "kernel": "4.19.0-11-amd64",
  "arch": "x64",
  "hostname": "fangorn",
  "codepage": "UTF-8",
  "logofile": "debian",
  "serial": "2a753bbe2f99452893073d05bfd9cbb1",
  "build": "",
  "servicepack": "",
  "uefi": false
}
```

## `chrysalis.json`

```json
{"version": "0.7.9"}
```

`logs.json` contains all our logs, the same ones we send to the developer console, while `device.json` contains information about the device:

```json
{
  "info": {
    "vendor": "Keyboardio",
    "product": "Model01",
    "displayName": "Keyboardio Model01",
    "urls": [
      {"name": "Homepage", "url": "https://shop.keyboard.io/"},
      {"name": "Forum", "url": "https://community.keyboard.io/"},
      {"name": "Chat", "url": "https://keyboard.io/discord-invite"}
    ]
  },
  "path": "/dev/ttyACM0",
  "commands": [
    "help",
    "version",
    "keymap.custom",
    "keymap.default",
    "keymap.onlyCustom",
    "palette",
    "colormap.map",
    "settings.defaultLayer",
    "settings.valid?",
    "settings.version",
    "settings.crc",
    "eeprom.contents",
    "eeprom.free",
    "hostos.type",
    "cycletime"
  ],
  "keymap": {
    "onlyCustom": true,
    "custom": [...],
    "default": [...]
  },
  "colormap": {
    "palette": [...],
    "colorMap": [...]
  }
}
```

2020-10-08 19:04 UTC, obra requested changes

2020-10-08 19:04 UTC, obra commented on src/renderer/i18n/en.js
> +    contents: `Chrysalis can collect a debug bundle you can share with the developers as a troubleshooting aid. The bundle will include information about your operating system and its version; Chrysa
If you're having trouble with Chrysalis, the development team may ask you to send them some debugging information. Chrysalis can help you collect and package up everything you might need to share. This includes error logs, as well as a bit of information about this computer's operating system, connected devices, and Chrysalis itself. Keyboard information will include information about the keyboard's current firmware, as well as key layouts and LED configuration. 

We try hard not to include private information in this bundle, but recommend you read through it before sharing it.

2020-10-08 19:04 UTC, obra commented on src/renderer/i18n/en.js
> +    collectButton: "Collect information",
Create Bundle

2020-10-08 19:04 UTC, obra commented
Awesome.

How hard would it be to show all of the information in a textarea on the save bundle page?

2020-10-08 19:07 UTC, algernon commented
It wouldn't be hard, but it's a _lot_ of info. How about I turn the `Create bundle` button into `View bundle` when the bundle is done? That'd pop up a dialog with a textarea, and a `Save bundle` button on top. (And we wouldn't have a save dialog appear during create then)

2020-10-08 19:08 UTC, obra commented
Thinking a little bit about the format - I think we either just want one json file or we want all of the files to include fingerprint information to tie them together:

reportInfo: { 
   chrysalisVersion: Blah,
   timestamp: DATETIMETHATISHTESAMEFORALLFILES,
   reportId: UUID-THAT-IS-THE-SAME-FOR-ALL-FILES-IN-THIS-REPORT
}

2020-10-08 19:09 UTC, algernon commented
I'd go with a single file then, that's a bit easier. But a timestamp and an UUID is a good idea regardless, so I'll add those to that single file anyway.

2020-10-08 19:10 UTC, algernon commented
Oh, and I'll still zip it, to make the bundle format future proof, in case we want to include screenshots or whatever later on.

2020-10-09 01:03 UTC, algernon commented
Updates:

## System Information

![Screenshot from 2020-10-09 02-58-42](https://user-images.githubusercontent.com/17243/95529530-6c09c700-09db-11eb-929b-534ff98dc5e6.png)

## After creating the bundle...

![Screenshot from 2020-10-09 02-58-45](https://user-images.githubusercontent.com/17243/95529542-76c45c00-09db-11eb-89e3-c7cb8e1b5369.png)

## View Bundle

![Screenshot from 2020-10-09 02-58-52](https://user-images.githubusercontent.com/17243/95529555-7d52d380-09db-11eb-9333-2edf865ebbee.png)

## After saving

![Screenshot from 2020-10-09 02-59-02](https://user-images.githubusercontent.com/17243/95529567-83e14b00-09db-11eb-9feb-190827bf12fd.png)

# Notes

When the `View Bundle` dialog is closed in any way, either by saving the bundle, or clicking the button, or pressing `Esc`, the component resets, and the user will have to create another bundle. The bundle now contains a single `bundle.json` file, which includes a timestamp and an UUID. The UUID isn't all that useful yet, but if we will include other files in the future, it will make it easier to match files up.

I'm pretty happy with the current state, so marking this as ready.

2020-10-09 01:44 UTC, merged